#!/usr/bin/env node
/**
 * generate-config.js
 * Writes config.js (window.ENV) for the browser.
 *
 * Priority order for each key:
 *   1. process.env  — Vercel / CI injects these at build time
 *   2. .env file    — local development fallback
 *
 * Local:  node generate-config.js
 * Vercel: runs automatically via vercel.json buildCommand
 */
const fs   = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');
const outPath = path.join(__dirname, 'config.js');

const KEYS = [
  'SUPABASE_URL',
  'SUPABASE_ANON_KEY',
  'GA_MEASUREMENT_ID',
];

/* ── 1. Start with process.env (populated by Vercel dashboard) ── */
const env = {};
KEYS.forEach(k => {
  if (process.env[k]) env[k] = process.env[k];
});

/* ── 2. Fill any missing keys from .env file (local dev) ── */
if (fs.existsSync(envPath)) {
  fs.readFileSync(envPath, 'utf8')
    .split('\n')
    .forEach(line => {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) return;
      const eq = trimmed.indexOf('=');
      if (eq === -1) return;
      const key = trimmed.slice(0, eq).trim();
      const val = trimmed.slice(eq + 1).trim().replace(/^['"]|['"]$/g, '');
      if (KEYS.includes(key) && !env[key]) env[key] = val; // process.env wins
    });
} else if (!Object.keys(env).length) {
  console.error('❌  No .env file and no process.env variables found.');
  process.exit(1);
}

/* ── 3. Write config.js ── */
const lines = KEYS.map(k => `  ${k.padEnd(18)}: '${env[k] || ''}',`).join('\n');

const isVercel = !!process.env.VERCEL;
const source   = isVercel ? 'Vercel environment variables' : '.env file';

const output = `/**
 * GATE Prep Hub — config.js
 * AUTO-GENERATED by generate-config.js (source: ${source})
 * Do not edit by hand. Do not commit to git.
 */
window.ENV = {
${lines}
};
`;

fs.writeFileSync(outPath, output, 'utf8');
console.log(`✅  config.js written from ${source}`);

/* ── 4. Warn about missing keys ── */
KEYS.forEach(k => {
  if (!env[k]) console.warn(`⚠️   ${k} is empty — check Vercel env vars or .env`);
});
