#!/usr/bin/env bash
# ─────────────────────────────────────────────
# generate-config.sh
# Reads .env and writes config.js for the browser.
#
# Usage:
#   chmod +x generate-config.sh   # first time only
#   ./generate-config.sh
# ─────────────────────────────────────────────
set -euo pipefail

ENV_FILE=".env"
OUT_FILE="config.js"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "❌  .env not found. Create one first."
  exit 1
fi

# Source the .env (ignore comment lines and blank lines)
while IFS='=' read -r key value; do
  [[ "$key" =~ ^#.*$ || -z "$key" ]] && continue
  # Trim whitespace and quotes
  key=$(echo "$key" | xargs)
  value=$(echo "$value" | xargs | sed "s/^['\"]//;s/['\"]$//")
  export "$key=$value"
done < "$ENV_FILE"

cat > "$OUT_FILE" << EOF
/**
 * GATE Prep Hub — config.js
 * ⚠️  AUTO-GENERATED by generate-config.sh — do not edit by hand.
 * ⚠️  DO NOT commit this file — it is listed in .gitignore
 */
window.ENV = {
  SUPABASE_URL:      '${SUPABASE_URL:-}',
  SUPABASE_ANON_KEY: '${SUPABASE_ANON_KEY:-}',
  GA_MEASUREMENT_ID: '${GA_MEASUREMENT_ID:-}',
};
EOF

echo "✅  config.js generated from .env"
